pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        
        //use SonarQube
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SCM') {

            checkout scm
        }
        stage('SonarQube Analysis') {

            def mvn = tool 'Default Maven';
            withSonarQubeEnv() {

            sh "${mvn}/bin/mvn sonar:sonar"
            
            }
        }
        //deploy to TomCat Web Server
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

    }
}
